backend:
  name: git-gateway
  branch: main

media_folder: "images/cast"
public_folder: "/JCS/images/cast"

collections:
  - name: "cast"
    label: "Cast Bios"
    folder: "data/cast-members"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
